In [1]:
a=1

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\hp\\Downloads\\Superstore sales dataset.csv")

In [3]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [4]:
df['Customer Name'].str.lower()

0            claire gute
1            claire gute
2        darrin van huff
3         sean o'donnell
4         sean o'donnell
              ...
9989    tom boeckenhauer
9990         dave brooks
9991         dave brooks
9992         dave brooks
9993        chris cortes
Name: Customer Name, Length: 9994, dtype: str

In [5]:
df['Customer Name'].str.upper()

0            CLAIRE GUTE
1            CLAIRE GUTE
2        DARRIN VAN HUFF
3         SEAN O'DONNELL
4         SEAN O'DONNELL
              ...
9989    TOM BOECKENHAUER
9990         DAVE BROOKS
9991         DAVE BROOKS
9992         DAVE BROOKS
9993        CHRIS CORTES
Name: Customer Name, Length: 9994, dtype: str

In [6]:
df['Customer Name'].str.len()

0       11
1       11
2       15
3       14
4       14
        ..
9989    16
9990    11
9991    11
9992    11
9993    12
Name: Customer Name, Length: 9994, dtype: int64

In [7]:
df['Customer Name'].str.strip()

0            Claire Gute
1            Claire Gute
2        Darrin Van Huff
3         Sean O'Donnell
4         Sean O'Donnell
              ...
9989    Tom Boeckenhauer
9990         Dave Brooks
9991         Dave Brooks
9992         Dave Brooks
9993        Chris Cortes
Name: Customer Name, Length: 9994, dtype: str

In [8]:
df['City'].str.replace("New York","NY")

0             Henderson
1             Henderson
2           Los Angeles
3       Fort Lauderdale
4       Fort Lauderdale
             ...
9989              Miami
9990         Costa Mesa
9991         Costa Mesa
9992         Costa Mesa
9993        Westminster
Name: City, Length: 9994, dtype: str

In [12]:
df[df['Product Name'].str.contains("Chair")]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,0.0,219.5820
23,24,US-2017-156909,16-07-2017,18-07-2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
39,40,CA-2015-117415,27-12-2015,31-12-2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,77041,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",212.058,3,0.3,-15.1470
52,53,CA-2015-115742,18-04-2015,22-04-2015,Standard Class,DP-13000,Darren Powers,Consumer,United States,New Albany,...,47150,Central,FUR-CH-10003061,Furniture,Chairs,"Global Leather Task Chair, Black",89.990,1,0.0,17.0981
57,58,CA-2016-111682,17-06-2016,18-06-2016,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,...,12180,East,FUR-CH-10003968,Furniture,Chairs,Novimex Turbo Task Chair,319.410,5,0.1,7.0980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9908,9909,US-2015-129007,13-09-2015,15-09-2015,First Class,KD-16615,Ken Dana,Corporate,United States,Anaheim,...,92804,West,FUR-FU-10002379,Furniture,Furnishings,Eldon Econocleat Chair Mats for Low Pile Carpets,207.350,5,0.0,24.8820
9912,9913,CA-2015-132388,10-10-2015,12-10-2015,First Class,KN-16390,Katherine Nockton,Corporate,United States,Santa Barbara,...,93101,West,FUR-CH-10001714,Furniture,Chairs,"Global Leather & Oak Executive Chair, Burgundy",362.136,3,0.2,-54.3204
9919,9920,CA-2016-149272,15-03-2016,19-03-2016,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,...,77803,Central,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,528.430,5,0.3,-143.4310
9947,9948,CA-2017-121559,01-06-2017,03-06-2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.880,6,0.0,539.2464
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332

In [13]:
df[df['Customer Name'].str.startswith("Chair")]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [14]:
df[df['Customer Name'].str.endswith("A")]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
912,913,CA-2015-133627,31-05-2015,07-06-2015,Standard Class,SC-20050,Sample Company A,Home Office,United States,Norwich,...,6360,East,FUR-FU-10001935,Furniture,Furnishings,3M Hangers With Command Adhesive,22.200,6,0.0,9.1020
2004,2005,US-2017-143028,11-04-2017,18-04-2017,Standard Class,SC-20050,Sample Company A,Home Office,United States,Lubbock,...,79424,Central,OFF-BI-10004738,Office Supplies,Binders,Flexible Leather- Look Classic Collection Ring...,11.364,3,0.8,-17.0460
3661,3662,CA-2016-155005,13-06-2016,15-06-2016,Second Class,SC-20050,Sample Company A,Home Office,United States,Jackson,...,49201,Central,TEC-PH-10003484,Technology,Phones,Ooma Telo VoIP Home Phone System,377.970,3,0.0,94.4925
4840,4841,CA-2017-154123,20-11-2017,25-11-2017,Standard Class,SC-20050,Sample Company A,Home Office,United States,Henderson,...,42420,South,FUR-FU-10000629,Furniture,Furnishings,9-3/4 Diameter Round Wall Clock,27.580,2,0.0,11.5836
4998,4999,CA-2016-129238,31-01-2016,04-02-2016,Standard Class,SC-20050,Sample Company A,Home Office,United States,Los Angeles,...,90045,West,TEC-PH-10004120,Technology,Phones,AT&T 1080 Phone,109.592,1,0.2,8.2194
4999,5000,CA-2016-129238,31-01-2016,04-02-2016,Standard Class,SC-20050,Sample Company A,Home Office,United States,Los Angeles,...,90045,West,OFF-PA-10002764,Office Supplies,Paper,Easy-staple paper,56.700,5,0.0,27.7830
5635,5636,CA-2017-123022,03-09-2017,08-09-2017,Standard Class,SC-20050,Sample Company A,Home Office,United States,La Mesa,...,91941,West,OFF-BI-10002225,Office Supplies,Binders,"Square Ring Data Binders, Rigid 75 Pt. Covers,...",82.560,5,0.2,28.8960
5636,5637,CA-2017-123022,03-09-2017,08-09-2017,Standard Class,SC-20050,Sample Company A,Home Office,United States,La Mesa,...,91941,West,TEC-AC-10000474,Technology,Accessories,Kensington Expert Mouse Optical USB Trackball ...,284.970,3,0.0,85.4910
7327,7328,US-2014-131275,18-03-2014,24-03-2014,Standard Class,SC-20050,Sample Company A,Home Office,United States,Burbank,...,91505,West,FUR-FU-10004597,Furniture,Furnishings,Eldon Cleatmat Chair Mats for Medium Pile Carpets,111.000,2,0.0,14.4300
7328,7329,US-2014-131275,18-03-2014,24-03-2014,Standard Class,SC-20050,Sample Company A,Home Office,United States,Burbank,...,91505,West,TEC-MA-10001148,Technology,Machines,Swingline SM12-08 MicroCut Jam Free Shredder,1279.968,4,0.2,415.9896
7329,7330,US-2014-131275,18-03-2014,24-03-2014,Standard Class,SC-20050,Sample Company A,Home Office,United States,Burbank,...,91505,West,OFF-ST-10000078,Office Supplies,Storage,Tennsco 6- and 18-Compartment Lockers,1856.190,7,0.0,334.1142
9687,9688,US-2017-130603,30-09-2017,06-10-2017,Standard Class,SC-20050,Sample Company A,Home Office,United States,Arlington,...,76017,Central,OFF-BI-10000301,Office Supplies,Binders,GBC Instant Report Kit,11.646,9,0.8,-17.4690
9769,9770,CA-2016-123533,24-11-2016,30-11-2016,Standard Class,SC-20050,Sample Company A,Home Office,United States,Hialeah,...,33012,South,FUR-BO-10001619,Furniture,Bookcases,O'Sullivan Cherrywood Estates Traditional Book...,339.920,5,0.2,8.4980
9770,9771,CA-2016-123533,24-11-2016,30-11-2016,Standard Class,SC-20050,Sample Company A,Home Office,United States,Hialeah,...,33012,South,OFF-PA-10001609,Office Supplies,Paper,Tops Wirebound Message Log Books,10.528,4,0.2,3.4216
9771,9772,CA-2016-123533,24-11-2016,30-11-2016,Standard Class,SC-20050,Sample Company A,Home Office,United States,Hialeah,...,33012,South,OFF-AP-10002765,Office Supplies,Appliances,Fellowes Advanced Computer Series Surge Protec...,42.384,2,0.2,4.2384

In [15]:
df['First Name']=df['Customer Name'].str.split().str[0]

In [16]:
df['Order Number']=df['Order ID'].str.extract('(\d+)')

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\hp\AppData\Local\Temp\ipykernel_552\713190355.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df['Order Number']=df['Order ID'].str.extract('(\d+)')

In [ ]:
## 20 MATHEMATICAL FUNCTIONS

In [17]:
df['Sales'].sum()

np.float64(2297200.8603)

In [18]:
df['Sales'].mean()

np.float64(229.85800083049827)

In [19]:
df['Sales'].median()

np.float64(54.489999999999995)

In [20]:
df['Quantity'].mode()

0    3
Name: Quantity, dtype: int64

In [21]:
df['Sales'].min()

np.float64(0.444)

In [23]:
df['Sales'].max()

np.float64(22638.48)

In [24]:
df['Sales'].count()

np.int64(9994)

In [25]:
df['Sales'].std()

np.float64(623.2451005086808)

In [26]:
df['Sales'].var()

np.float64(388434.45530807565)

In [27]:
df['Quantity'].prod()

np.int64(0)

In [ ]:
df['Sales'].cumsum()

0       2.619600e+02
1       9.939000e+02
2       1.008520e+03
3       1.966098e+03
4       1.988466e+03
            ...
9989    2.296578e+06
9990    2.296670e+06
9991    2.296928e+06
9992    2.296958e+06
9993    2.297201e+06
Name: Sales, Length: 9994, dtype: float64

In [30]:
df['Sales'].cummax()

0         261.9600
1         731.9400
2         731.9400
3         957.5775
4         957.5775
           ...
9989    22638.4800
9990    22638.4800
9991    22638.4800
9992    22638.4800
9993    22638.4800
Name: Sales, Length: 9994, dtype: float64

In [31]:
df['Sales'].cummin()

0       261.960
1       261.960
2        14.620
3        14.620
4        14.620
         ...
9989      0.444
9990      0.444
9991      0.444
9992      0.444
9993      0.444
Name: Sales, Length: 9994, dtype: float64

In [32]:
df['Sales'].cumprod()

c:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages\numpy\_core\fromnumeric.py:54: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)

0       2.619600e+02
1       1.917390e+05
2       2.803224e+06
3       2.684304e+09
4       6.004252e+10
            ...
9989             inf
9990             inf
9991             inf
9992             inf
9993             inf
Name: Sales, Length: 9994, dtype: float64

In [34]:
df['Profit'].abs()

0        41.9136
1       219.5820
2         6.8714
3       383.0310
4         2.5164
          ...
9989      4.1028
9990     15.6332
9991     19.3932
9992     13.3200
9993     72.9480
Name: Profit, Length: 9994, dtype: float64

In [35]:
df['Sales'].round(2)

0       261.96
1       731.94
2        14.62
3       957.58
4        22.37
         ...
9989     25.25
9990     91.96
9991    258.58
9992     29.60
9993    243.16
Name: Sales, Length: 9994, dtype: float64

In [36]:
df['Sales']**2

0        68623.041600
1       535736.163600
2          213.744400
3       916954.668506
4          500.327424
            ...
9989       637.461504
9990      8456.641600
9991     66861.547776
9992       876.160000
9993     59126.785600
Name: Sales, Length: 9994, dtype: float64

In [42]:
import numpy as np

In [43]:
np.sqrt(df['Sales'])

0       16.185178
1       27.054390
2        3.823611
3       30.944749
4        4.729482
          ...
9989     5.024739
9990     9.589578
9991    16.080299
9992     5.440588
9993    15.593588
Name: Sales, Length: 9994, dtype: float64

In [44]:
df['Sales'].corr(df['Profit'])

np.float64(0.4790643497377061)

In [45]:
df['Profit_Margin']=(df['Profit']/df['Sales'])*100#20.

In [ ]:
df.groupBy examples (Bonus)